import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const primary = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${primary.className} antialiased bg-[#161616]`}>
        {children}
      </body>
    </html>
  );
}
